### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ckrsls** [jc211/ParticleNeRF#6]
CMakeFiles/Makefile2:307: recipe for target 'CMakeFiles/ngp.dir/all' failed
make[1]: *** [CMakeFiles/ngp.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jc211** [comment]
Sorry that is not enough information for me to help

**Comment by ckrsls** [comment]
Thanks for your reply, I solved the problem by simply adding --recursive after git clone to download all the submodules. But I still have a question, is there an easy way to extract the particle encoding part so that it can be connected with the MLP decoder implemented by pytorch?
